# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 707c2a2ac412a20346108829a4a6a78a701b63fee6f978931fe208a2a092dfc2697db64c26a03434ae4ab59f5d5fc40c9a6ab24bc270390c1e7270c36bb5e700

test:
  secret_key_base: 14d453859b1d0515fe3c842b4c9017c94be9045811c24f6b55b738fd18b114a749d06708d5be96787098688c3cae604cf196cc993db9267d923c0d14a0b089fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
